
name: funny jokes

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  test: funny joke

    runs-on:ubuntu-latest

    steps:
    - uses: 
    - name: 
    
      uses:
      with:
        ruby-version: 2.6
    - name: 
      run: 
    - name: 
      run: 
- name: 
  uses: 
  with:
    
    always-auth: 
    
    node-version: 
    
    
    registry-url: 
    scope:.
    token:
    version: 
